### ISSUE TITLE
wrong php array formatting in html code

### ISSUE THREAD

**Issue by tariqalkhassa** [RiFi2k/format-html-in-php#14] opened 2019-01-14 15:10 UTC
I have an html code like this:
```
<div>
    <input type="text" value="<?=$x["test"] . $x['test']?>">
</div>
```

when I format it it adds a space at the start of the array keys 
so the $x["test"] becomes: $x[" test"] like this:

```
<div>
    <input type="text" value="<?=$x[" test"] . $x['test']?>">
</div>
```

the same is happening when changing double quotes to a single quote of the value html attribute but at this time the space is being added to the other key i.e. `value='<?=$x["test"] . $x['test']?>'` becomes `value='<?=$x["test"] . $x[' test']?>'`

**Comment by tariqalkhassa** [comment] 2019-01-14 15:30
> @tariqalkhassa Can you try the same but switch to not using the short PHP tags and tell me if you get the same result?

@RiFi2k I've tried with <?php echo $x["test"] . $x['test'] ?> but I'm getting the same result

**Comment by RiFi2k** [comment] 2019-01-14 15:32
Thanks, I'll take a look and see what the problem is.

**Comment by tariqalkhassa** [comment] 2019-01-14 15:35
Thanks @RiFi2k . 
I think that when we write `value="<?=$x[" test"] . $x['test']?>">` the extension thinks that the part
 `"<?=$x["` is an html attribute so it adds a space after the qutation.

**Comment by RiFi2k** [comment] 2019-01-14 15:38
Yeah, good call I can see exactly what you mean. That is totally the issue if I had to guess.

**Comment by RiFi2k** [comment] 2019-01-17 09:41
Ended up checking with one of the awesome maintainers of js-beautify and he told me they would [fix it upstream](https://github.com/beautify-web/js-beautify/issues/1620).

You can demo it out right now on https://beautifier.io/ it's fixed in v1.9.0-beta2

Just going to give it a bit more time till it graduates to a patch release and I'll merge it in.

**Comment by tariqalkhassa** [comment] 2019-01-17 10:42
Ok thanks bor

**Comment by RiFi2k** [comment] 2019-01-23 11:44
Upgraded, thanks for the report. Let me know if you still have issues.

**Closed by RiFi2k** 2019-01-23 11:44 UTC
Labels: bug, upstream

**Comment by tariqalkhassa** [comment] 2019-02-06 11:08
Hello,
I'm found a new problem now
if I have a php code inside script tags like this:

```
<script>
<? if (true) { ?>
alert('test');
<? } ?>
</script>
```

a space is being added between '<' and '?' so it becomes like this after formatting :

```
<script>
< ?
if (true) {
    ? >
    alert('test'); <
    ?
} ? >
</script>
```
