### ISSUE TITLE
Broken PHP syntax inside <script> tags in vscode

### ISSUE THREAD

**Issue by abhijeetdhariwal** [RiFi2k/format-html-in-php#37] opened 2020-03-13 06:18 UTC
<style>
                                #contact-map {
                                    width: 100%;
                                    height: 400px;
                                    margin: 0 auto;
                                }
                                </style>

                                <div id="contact-map"></div>

                                <script type="text/javascript">
                                /*=== initializate google map ====*/

                                function initMap() {

                                    var styles = [{
                                            "featureType": "administrative",
                                            "elementType": "all",
                                            "stylers": [{
                                                    "visibility": "on"
                                                },
                                                {
                                                    "saturation": -100
                                                },
                                                {
                                                    "lightness": 20
                                                }
                                            ]
                                        },
                                        {
                                            "featureType": "road",
                                            "elementType": "all",
                                            "stylers": [{
                                                    "visibility": "on"
                                                },
                                                {
                                                    "saturation": -100
                                                },
                                                {
                                                    "lightness": 40
                                                }
                                            ]
                                        },
                                        {
                                            "featureType": "water",
                                            "elementType": "all",
                                            "stylers": [{
                                                    "visibility": "on"
                                                },
                                                {
                                                    "saturation": -10
                                                },
                                                {
                                                    "lightness": 30
                                                }
                                            ]
                                        },
                                        {
                                            "featureType": "landscape.man_made",
                                            "elementType": "all",
                                            "stylers": [{
                                                    "visibility": "simplified"
                                                },
                                                {
                                                    "saturation": -60
                                                },
                                                {
                                                    "lightness": 10
                                                }
                                            ]
                                        },
                                        {
                                            "featureType": "landscape.natural",
                                            "elementType": "all",
                                            "stylers": [{
                                                    "visibility": "simplified"
                                                },
                                                {
                                                    "saturation": -60
                                                },
                                                {
                                                    "lightness": 60
                                                }
                                            ]
                                        },
                                        {
                                            "featureType": "poi",
                                            "elementType": "all",
                                            "stylers": [{
                                                    "visibility": "off"
                                                },
                                                {
                                                    "saturation": -100
                                                },
                                                {
                                                    "lightness": 60
                                                }
                                            ]
                                        },
                                        {
                                            "featureType": "transit",
                                            "elementType": "all",
                                            "stylers": [{
                                                    "visibility": "off"
                                                },
                                                {
                                                    "saturation": -100
                                                },
                                                {
                                                    "lightness": 60
                                                }
                                            ]
                                        }
                                    ];

                                    <
                                    ?
                                    php
                                    if ($local_location) {
                                        ?
                                        >

                                        var myLatLng = {
                                            lat: < ? php echo esc_js($PIXAD_Autos - > get_meta(
                                                '_seller_location_lat')) ? > ,
                                            lng: < ? php echo esc_js($PIXAD_Autos - > get_meta(
                                                '_seller_location_long')) ? >
                                        };
                                        var address =
                                            "<?php echo esc_js($PIXAD_Autos->get_meta('_seller_location')) ?>";

                                        <
                                        ?
                                        php
                                    }
                                    elseif($global_location) {
                                            ?
                                            >

                                            var myLatLng = {
                                                lat: < ? php echo esc_js($validate[
                                                    'seller-location-lat_def']) ? > ,
                                                lng: < ? php echo esc_js($validate[
                                                    'seller-location-long_def']) ? >
                                            };
                                            var address =
                                                "<?php echo esc_js($validate['seller-location_def']) ?>";

                                            <
                                            ?
                                            php
                                        } ? >

                                        // Create a map object and specify the DOM element for display.
                                        var map = new google.maps.Map(document.getElementById(
                                            "contact-map"), {
                                            center: myLatLng,
                                            scrollwheel: false,
                                            zoom: 15
                                        });

                                    var marker = new google.maps.Marker({
                                        position: myLatLng,
                                        map: map,
                                        title: address
                                    });

                                    map.setOptions({
                                        styles: styles
                                    });

                                }
                                </script>

**Comment by chriscoyier** [comment] 2020-05-04 23:24
Same issue...

```
<script>
  var articleYear = <?php the_time('Y') ?>;
</script>
```

Becomes...

```
<script>
var articleYear = < ? php the_time('Y') ? > ;
</script>
```

**Comment by abhijeetdhariwal** [comment] 2020-05-05 07:28
Use like this


<script>
  var articleYear = '<?php the_time('Y') ?>';
</script>

**Comment by kpmarino** [comment] 2020-07-14 21:16
see a problem with that solution. if the value is numeric there is no need for outer quotes.

**Comment by bitwiseman** [comment] 2020-09-21 16:53
Duplicate of #31

**Closed** 2020-09-23 19:13 UTC
